# Generated by Django 4.2.16 on 2024-11-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('is_edible', models.BooleanField()),
                ('used_for', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='images/')),
                ('category', models.CharField(choices=[('FLOWERS', 'Flowers'), ('GRASSES', 'Grasses'), ('TREES', 'Trees'), ('FRUITS', 'Fruits')], max_length=20)),
            ],
        ),
    ]
