# Generated by Django 4.2.16 on 2024-11-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='about',
            field=models.TextField(default='The tree is essintial to the environement and help produce fresh air'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('FLOWERS', 'Flowers'), ('TREES', 'Trees'), ('FRUITS', 'Fruits')], default='TREES', max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='is_edible',
            field=models.BooleanField(default=False),
        ),
    ]
